version: 0.2

env:
  parameter-store:
    ecr_ak: "China-ECR-AK"
    ecr_sk: "China-ECR-SK"

phases:
  install:
    runtime-versions:
        python: 3.10

  pre_build:
    commands:
      - pip install -r src/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
      - wget https://github.com/lework/skopeo-binary/releases/latest/download/skopeo-linux-amd64 && chmod +x skopeo-linux-amd64 && mv skopeo-linux-amd64 /usr/bin/skopeo

  build:
    commands:
      - python src/main.py